platforms:
  - name: 微博
    weight: 0.3
  - name: 抖音
    weight: 0.2
  - name: 小红书
    weight: 0.12
  - name: 今日头条
    weight: 0.1
  - name: 百度热点
    weight: 0.08
  - name: 哔哩哔哩
    weight: 0.06
  - name: 快手
    weight: 0.05
  - name: 虎扑
    weight: 0.05
  - name: 豆瓣小组
    weight: 0.02
  - name: 澎湃新闻
    weight: 0.01
  - name: 知乎热榜
    weight: 0.01
publish_platform: wechat
wechat:
  credentials:
    - appid: ""
      appsecret: ""
      author: ""
      call_sendall: false
      sendall: true
      tag_id: 0
    - appid: ""
      appsecret: ""
      author: ""
      call_sendall: false
      sendall: true
      tag_id: 0
    - appid: ""
      appsecret: ""
      author: ""
      call_sendall: false
      sendall: true
      tag_id: 0
api:
  api_type: OpenRouter
  Grok:
    key: XAI_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - xai/grok-3
    api_base: https://api.x.ai/v1/chat/completions
  Qwen:
    key: OPENAI_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - openai/qwen-plus
    api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
  Gemini:
    key: GEMINI_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - gemini/gemini-1.5-flash
      - gemini/gemini-1.5-pro
      - gemini/gemini-2.0-flash
    api_base: https://generativelanguage.googleapis.com/v1beta/openai/
  OpenRouter:
    key: OPENROUTER_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - openrouter/deepseek/deepseek-chat-v3-0324:free
      - openrouter/deepseek/deepseek-r1-0528:free
      - openrouter/deepseek/deepseek-prover-v2:free
      - openrouter/deepseek/deepseek-r1:free
      - openrouter/deepseek/deepseek-chat:free
      - openrouter/qwen/qwen3-32b:free
      - openrouter/qwen/qwq-32b:free
      - openrouter/google/gemini-2.0-flash-lite-preview-02-05:free
      - openrouter/google/gemini-2.0-flash-thinking-exp:free
    api_base: https://openrouter.ai/api/v1
  Ollama:
    key: OPENAI_API_KEY
    key_index: 0
    api_key:
      - tmp-key
    model_index: 0
    model:
      - ollama/deepseek-r1:14b
      - ollama/deepseek-r1:7b
    api_base: http://localhost:11434
  Deepseek:
    key: DEEPSEEK_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - deepseek/deepseek-chat
      - deepseek/deepseek-reasoner
    api_base: https://api.deepseek.com/v1
  SiliconFlow:
    key: OPENAI_API_KEY
    key_index: 0
    api_key:
      - ""
    model_index: 0
    model:
      - openai/deepseek-ai/DeepSeek-V3
      - openai/deepseek-ai/DeepSeek-R1
      - openai/Qwen/QwQ-32B
      - openai/Qwen/Qwen3-32B
    api_base: https://api.siliconflow.cn/v1
img_api:
  api_type: picsum
  ali:
    api_key: ""
    model: wanx2.0-t2i-turbo
  picsum:
    api_key: ""
    model: ""
use_template: true
template_category: ""
template: ""
use_compress: true
aiforge_search_max_results: 10
aiforge_search_min_results: 1
min_article_len: 1000
max_article_len: 2000
auto_publish: true
article_format: html
format_publish: true
creative_mode: ""
creative_config:
  style_transform:
    enabled: false
    style_target: "shakespeare"
    available_styles:
      - "shakespeare"
      - "detective"
      - "scifi"
      - "classical_poetry"
      - "modern_poetry"
      - "academic"
      - "news"
  time_travel:
    enabled: false
    time_perspective: "ancient"
    available_perspectives:
      - "ancient"
      - "modern"
      - "future"
  role_play:
    enabled: false
    role_character: "libai" # 默认选择
    available_roles:
      # 古典诗词
      - "libai" # 李白 - 浪漫主义诗人
      - "dufu" # 杜甫 - 现实主义诗人
      - "sushi" # 苏轼 - 豪放派词人
      - "liqingzhao" # 李清照 - 婉约派词人

      # 古典小说
      - "caoxueqin" # 曹雪芹 - 《红楼梦》作者
      - "shinaian" # 施耐庵 - 《水浒传》作者
      - "wuchengen" # 吴承恩 - 《西游记》作者
      - "pusonglin" # 蒲松龄 - 《聊斋志异》作者

      # 现代文学
      - "luxun" # 鲁迅 - 现代文学奠基人
      - "laoshe" # 老舍 - 人民艺术家
      - "bajin" # 巴金 - 现代作家
      - "qianjunru" # 钱钟书 - 学者作家

      # 武侠小说
      - "jinyong" # 金庸 - 武侠小说大师
      - "gulongxia" # 古龙 - 新派武侠代表

      # 新闻主播/评论员
      - "baiyansong" # 白岩松 - 央视主持人
      - "cuiyongyuan" # 崔永元 - 知名主持人
      - "yanglan" # 杨澜 - 媒体人
      - "luyu" # 鲁豫 - 访谈节目主持人

      # 音乐人
      - "zhoujielun" # 周杰伦 - 流行音乐天王
      - "denglijun" # 邓丽君 - 华语歌坛传奇
      - "lironghao" # 李荣浩 - 创作型歌手

      # 相声曲艺
      - "guodegang" # 郭德纲 - 相声演员
      - "zhaobenshang" # 赵本山 - 小品演员

      # 自定义
      - "custom" # 自定义人物
    custom_character: "" # 自定义人物名称
  combination_mode: false
